project:
  type: website

website:
  title: "Aniket Deshpande"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    toc: true



